Import and reload module example
#+begin_src python :results output
  import script1
  from importlib import reload
  reload(script1)
#+end_src

#+RESULTS:
: linux
: 1267650600228229401496703205376
: Spam!Spam!Spam!Spam!Spam!Spam!Spam!Spam!
: linux
: 1267650600228229401496703205376
: Spam!Spam!Spam!Spam!Spam!Spam!Spam!Spam!

Access to module attribute
#+begin_example myfile.py
title = "The Meaning of Life"
#+end_example

#+begin_src python :results output
  import myfile          # Run file; load module as a whole
  print(myfile.title)    # Use its attribute names: '.' to qualify
#+end_src

#+RESULTS:
: The Meaning of Life

the dot expression syntax =object.attribute=

#+begin_src python :results output
  from myfile import title   # Run file; copy its names
  print(title)               # Use name directly: no need to qualify
#+end_src

#+RESULTS:
: The Meaning of Life

#+begin_src python :results output
  import threenames
  print(threenames.b, threenames.c)
  print(dir(threenames))
#+end_src

#+RESULTS:
: dead parrot sketch
: parrot sketch
: ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'a', 'b', 'c']

When the =dir= function is called with the name of an imported module
passed in parentheses like this, it returns all
the attributes inside that module.

#+begin_src python :results output
  from threenames import a, b, c
  print(b, c)
#+end_src

#+RESULTS:
: dead parrot sketch
: parrot sketch

The exec(open('module.py').read()) built-in function call is another
way to launch files from the interactive prompt without having to
import and later reload:
#+begin_src python :results output
exec(open('script1.py').read())
#+end_src

#+RESULTS:
: linux
: 1267650600228229401496703205376
: Spam!Spam!Spam!Spam!Spam!Spam!Spam!Spam!

Python searches for imported modules in every directory listed in
sys.path —a Python list of directory name strings in the sys module,
which is initialized from a PYTHONPATH environment variable, plus a
set of standard directories. If you want to import from a directory
other than the one you are working in, that directory must generally
be listed in your PYTHONPATH setting.
