
SCHEDULED: <2023-12-08 Fri>

The word "practice" often associates with "regularly repeated
actions" - sports exercises, cooking, text typing, vocabulary
repetition.

But just repeating a skill or task, even over a period of many years,
doesn’t build experience. Many people give up on learning a new skill
or only reach a middling level of competence because they are not
making much progress. That’s because once you reach a reasonable level
of competence and are able to do what you need to do, the skill
becomes automatic. At best, you’re maintaining your abilities, but not
improving them.


* RAW Several definitions
SCHEDULED: <2023-12-11 Mon>

*Practice* is a repetition of an activity to improve a skill.

*Deliberate practice* is a system of regularly repetitive conscious
learning activities that are conducted for improving an individual's
skills and performance that requires many cognitive efforts, maximum
focus. Deliberate practice is conducted with the goal of improving an
individual's productivity and build experience.


* RAW Real life samples
SCHEDULED: <2023-12-10 Sun>
:LOGBOOK:
CLOCK: [2023-12-08 Fri 08:15]--[2023-12-08 Fri 09:00] =>  0:45
:END:

Benjamin Franklin: A self-educated writer.

Benjamin Franklin had been inspired by the quality and style of
articles in a British magazine he read, and wanted to improve his own
writing. He wide used the principles of deliberate practice into
action. He tried to replicate the texts from the magazine. To help
himself, he wrote short notes of the magazine’s content, so he could
be restored of the meaning of each sentence. Franklin wanted to create
his own articles by his own words that were just as detailed, witty,
and neatly written as the original. When he compared his work to the
original, he would identify common instances where his writing fell
short and refine this practice technique to focus on those particular
weaknesses.

* RAW Deliberate practice rules
SCHEDULED: <2023-12-11 Mon>

1. Be inspired, engaged and motivated. It will helps in the hard parts
   of learning process - the frustration, the failures, the slow
   progres period;
2. Break the overall learning process down into small chunks;
3. Identify your weaknesses, test new strategies for each chunk;
4. Integrate your new learning experience into the overall process;
5. Delibarate practice requires recovery time. The process requires
   maximum focus and attention. It is challenging and impossible to do
   it all day long. The overall duration should not exeed 2 hours per
   day;
6. Search the constructive feedback and measurement. Good tutor can
   track your progress, find small ways to improve, and hold you
   accountable to delivering your best effort each day.

* INIT Conclusion
SCHEDULED: <2023-12-11 Mon>

Regular repetition helps to improve speed, increased confidence but
doesn't improve our performance.

Mindness activity is the enemy of learning because our progress
becomes imaginated. We think what we are gained experience. But we
only reinforcing our current habits.

Deliberate practice have no immediate reward. Important to be
consistent and persistent.

Delibarate practice help us to maximize our potential.
