#+BEGIN_EXPORT html
---
layout: post
title: Nice and dice
subtitle: feel and view
permalink: /blog-mark-up.html
categories: [Learning, Methodology]
tags: [emacs, org-mode, org-agenda, double-loop-learning]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Methodolody
#+TODO: RAW INIT TODO ACTIVE | DONE

* RAW Preface
SCHEDULED: <2023-11-30 Thu ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-21 Tue 18:11]
:END:
- State "DONE"       from "ACTIVE"     [2023-11-21 Tue 18:11]
- State "DONE"       from "ACTIVE"     [2023-11-17 Fri 08:56]
- State "DONE"       from "ACTIVE"     [2023-11-13 Mon 12:03]


  Searching  your ways and approaches for learning and process information
  is a complex and constantly evolving process.
  They can impact how you understand, retain and apply new material.
  However it is utter importance find it if you want achieve the best learning outcome and
  your solid base of personal knowledge.
  
  
* RAW What is methodology
 SCHEDULED: <2023-11-30 Thu ++4d>
 :PROPERTIES:
 :LAST_REPEAT: [2023-11-23 Thu 11:38]
 :END:
 - State "DONE"       from "ACTIVE"     [2023-11-23 Thu 11:38]
 - State "DONE"       from "ACTIVE"     [2023-11-19 Sun 12:38]
 - State "DONE"       from "ACTIVE"     [2023-11-15 Wed 09:03]
 :LOGBOOK:
 CLOCK: [2023-11-15 Wed 08:01]--[2023-11-15 Wed 09:03] =>  1:02
 :END:
 A "methodology" is a system of methods and principles in particular area
 to perform some complex task.

 System is a regularly interacting or interdependent group of items forming a unified whole.
 A set of connected things or devices that operate together.

 Method is a particular way of doing something.

 Principle - is a basic idea or rule that explains or controls how something happens or works.
 Basic rules or laws.

 I define learning methodology simply as your strategical understanding of
 how you receive information to best learn.

* RAW What methodology means in learning
SCHEDULED: <2023-11-30 Thu ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-20 Mon 16:13]
:END:

- State "DONE"       from "ACTIVE"     [2023-11-20 Mon 16:13]
- State "DONE"       from "ACTIVE"     [2023-11-16 Thu 08:30]
Learning methodology is a system of methods, principles and practices
used to effective learning.

In essence it is the learning of how to learn.

There are several techniques and learning methods that will not only
help in the learning process itself, but will help make the learning
process more effective and also help you achieve the best result.
They are include:

Double loop learning - is an iterative model which posits that
higher-order learning involves two processes or loops.

#+begin_quote
In double loop learning, problems are examined and corrected even
though correction requires challenge to underlying policies and
objectives.

Single loop learning - this form of learning aims at solving the
increasing changes and the problems that have risen as a consequence
of this. However, this ignores the real cause of the problem.

Double loop learning - this form of learning will go more deeply into
the cause of the problem and feedback is used to look at past actions.
#+end_quote


Pomodoro technique

#+begin_quote
The Pomodoro Technique is a time management method developed by
Francesco Cirillo in the late 1980s. It uses a kitchen timer to break
work into intervals, typically 25 minutes in length, separated by
short breaks. Each interval is known as a pomodoro
#+end_quote

Feyman's technique

#+begin_quote
The Feynman Technique, developed by Richard Feynman, is a study method
for students to learn through the act of teaching. To use the
technique, students choose a topic and then explain it in their own
words as if teaching a sixth-grader. Then, they improve their
explanations and go through the process again until they have mastered.
#+end_quote

Deliberate practice

#+begin_quote
Deliberate practice refers to a special type of practice that is
purposeful and systematic. While regular practice might include
mindless repetitions, deliberate practice requires focused attention
and is conducted with the specific goal of improving performance.
#+end_quote

Spaced repetition

#+begin_quote
Spaced repetition is a memory technique that involves reviewing and
recalling information at optimal spacing intervals until the
information is learned. It helps your brain remember more information,
reduces forgetting, and improves long-term memory recall.

"Spaced repetition" is when you repeatedly revisit material at
designated intervals. Author Barbara Oakley advises using this
strategy with active recall studying because it will engrain the
information in your memory better than the same amount of study
crammed into a single session.
#+end_quote

* RAW How practically prepare yourself to studying
SCHEDULED: <2023-11-30 Thu ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-23 Thu 11:38]
:END:


- State "DONE"       from "ACTIVE"     [2023-11-23 Thu 11:38]
- State "DONE"       from "ACTIVE"     [2023-11-19 Sun 12:38]
- State "DONE"       from "ACTIVE"     [2023-11-15 Wed 09:24]

Preparing yourself mentally to learn is essential for a successful and
fulfilling learning process and futher best result.
Before you start your learning, answer yourself the questions:

- What do I want to achieve in life?
- What are the reasons I chose this specialty?
- Where do I want to see myself in 5 years? In 10 yrs?
- What do I need to do to reach those goals?

If you feel like you have too much to study or don't know where to start
break your studying into manageable chunks and create a study plan to help
you stay organized.

Determine the list of educational material that you need to study.
Find the best sources for this material.
For each subject it is necessary to draw up a list of questions that need
to be studied.

The workplace should be clean without unnecessary objects. So that you are
not distracted and be able to focus as much as possible.
Get enough sleep before studying. Eat less can make your brain more clear and easier
to focus on the task.

* RAW [#C] What is the average time you should spend on each session
SCHEDULED: <2023-11-30 Thu ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-21 Tue 18:11]
:END:

- State "DONE"       from "ACTIVE"     [2023-11-21 Tue 18:11]
- State "DONE"       from "ACTIVE"     [2023-11-17 Fri 08:04]
As an implementation of =double-loop-learning= approach might be
convenient to use these words in your ~TODO~ sequence during studying
computer science and programming:

#+begin_example
RAW Init DP0 Todo DP1 Active | Done
#+end_example


 - RAW state is for just captured and unscheduled yet tasks;
 - After scheduling and Initial dissection task its status switches
   (++1d/2d) on to DeliberatePractice0 status;
 - After that (++1d/2d) it's time Todo the second loop in studying theory;
 - And soon (++1d/2d) it's very moment to another DP1 session;
 - Now material is well prepapared to be a handy tool in your hands
   and it is reasonably to shift a week ahead for final rehersal;
 - After that it's nothing to add - use these piece of knowledge and
   have fun out from it!


 #+begin_quote
All relevant questions should be questioned while task resolving.
 #+end_quote
 
 So, you *must* write these questions down during session and answer
 they a little bit later.


* RAW Initial chapter dissection
SCHEDULED: <2023-11-30 Thu ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-21 Tue 18:12]
:END:

- State "DONE"       from "ACTIVE"     [2023-11-21 Tue 18:12]
- State "DONE"       from "ACTIVE"     [2023-11-17 Fri 08:55]
At the Initial chapter dissection stage, I begin a detailed study of the material:

 - I find the relevant theoretical material;
 - Determine a list of questions that I need to learn;
 - Schedule each question;
 - Start to learn each question in detail using Pomodoro technique
   and extract of marrow from each studied material;
 - I write down all the questions that arise. 
   
* RAW Deliberate practice 0 session
SCHEDULED: <2023-11-30 Thu ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-21 Tue 18:12]
:END:

- State "DONE"       from "ACTIVE"     [2023-11-21 Tue 18:12]
- State "DONE"       from "ACTIVE"     [2023-11-17 Fri 08:55]
On this stage I use pseudo tests from the books and practice with them
in my Python Interpreter and using Org-babel source code
opportunity. It partially allows me to understand how it works.

* ToDo session

Describe what you ought to do and in what manner it might be
implemented.


* Deliberate practice 1 session

Describe what you ought to do and in what manner it might be
implemented.


* Active session


Describe what you ought to do and in what manner it might be
implemented.



* Conclusion
