#+BEGIN_EXPORT html
---
layout: post
title: Nice and dice
subtitle: feel and view
permalink: /blog-mark-up.html
categories: [Learning, Methodology]
tags: [emacs, org-mode, org-agenda, double-loop-learning]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Methodolody
#+TODO: RAW INIT TODO ACTIVE | DONE

* RAW Preface
SCHEDULED: <2023-11-17 Fri ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-13 Mon 12:03]
:END:
- State "DONE"       from "ACTIVE"     [2023-11-13 Mon 12:03]


Searching  your ways and approaches for learning and process information
  is a complex and constantly evolving process.
  They can impact how you understand, retain and apply new material.
  However it is utter importance find it to achieving the best learning outcome and
  your solid base of personal knowledge.
  
  
* RAW What is methodology
 SCHEDULED: <2023-11-19 Sun ++4d>
 :PROPERTIES:
 :LAST_REPEAT: [2023-11-15 Wed 09:03]
 :END:
 - State "DONE"       from "ACTIVE"     [2023-11-15 Wed 09:03]
 :LOGBOOK:
 CLOCK: [2023-11-15 Wed 08:01]--[2023-11-15 Wed 09:03] =>  1:02
 :END:
A "methodology" is a system of methods and principles in particular area
to perform some complex task.

System is a regularly interacting or interdependent group of items forming a unified whole.
A set of connected things or devices that operate together.

Method is a particular way of doing something.

Principle - is a basic idea or rule that explains or controls how something happens or works.
Basic rules or laws.

  I define learning methodology simply as your strategical understanding of
  how you receive information to best learn.

* RAW What methodology means in learning
SCHEDULED: <2023-11-16 Thu ++4d>

Learning methodology is a system of  methods, principles and practices
used to effective learning.

In essence it is the learning of how to learn.

Learning methodologies and activities include:

Double loop learning approach
Pomodoro technique
Brainstorming
Extract of marrow from each studied material
Feyman's technique
Deliberate practice
Spaced repetition

* RAW How practically prepare yourself to studying
SCHEDULED: <2023-11-19 Sun ++4d>
:PROPERTIES:
:LAST_REPEAT: [2023-11-15 Wed 09:24]
:END:


- State "DONE"       from "ACTIVE"     [2023-11-15 Wed 09:24]
Before you start your learning, answer yourself the questions:

1. What do I want to achieve in life?
2. What are the reasons I chose this specialty?
3. Where do I want to see myself in 5 years? In 10 yrs?
4. What do I need to do to reach those goals?

If you feel like you have too much to study or don't know where to start
break your studying into manageable chunks and create a study plan to help
you stay organized.

Determine the list of educational material that you need to study.
Find the best sources for this material.
For each subject it is necessary to draw up a list of questions that need
to be studied.

The workplace should be clean without unnecessary objects. So that you are
not distracted and be able to focus as much as possible.
Get enough sleep before studying. Eat less can make your brain more clear and easier
to focus on the task.

* What is the average time you should spend on each session

As an implementation of =double-loop-learning= approach might be
convenient to use these words in your ~TODO~ sequence during studying
computer science and programming:

#+begin_example
RAW Init DP0 Todo DP1 Active | Done
#+end_example


 - RAW state is for just captured and unscheduled yet tasks;
 - After scheduling and Initial dissection task its status switches
   (++1d/2d) on to DeliberatePractice0 status;
 - After that (++1d/2d) it's time Todo the second loop in studying theory;
 - And soon (++1d/2d) it's very moment to another DP1 session;
 - Now material is well prepapared to be a handy tool in your hands
   and it is reasonably to shift a week ahead for final rehersal;
 - After that it's nothing to add - use these piece of knowledge and
   have fun out from it!


 #+begin_quote
All relevant questions should be questioned while task resolving.
 #+end_quote
 
 So, you *must* write these questions down during session and answer
 they a little bit later.



* Initial chapter dissection

Describe what you ought to do and in what manner it might be
implemented.


* Deliberate practice 0 session

Describe what you ought to do and in what manner it might be
implemented.


* ToDo session

Describe what you ought to do and in what manner it might be
implemented.


* Deliberate practice 1 session

Describe what you ought to do and in what manner it might be
implemented.


* Active session


Describe what you ought to do and in what manner it might be
implemented.



* Conclusion
