#+BEGIN_EXPORT html
---
layout: post
title: Delibarate practice 
subtitle: feel and view
permalink: /deleberate-practice.html
categories: [Learning, Methodology]
tags: [practice, double-loop-learning]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Meta
#+TODO: RAW INIT TODO ACTIVE | DONE

* TODO [#B] Preface
SCHEDULED: <2024-02-01 Thu>
:PROPERTIES:
:END:

#+begin_quote
/"Practice makes perfect."/
#+end_quote

Practice makes proficient employees, and proficient employees make for
a successful business.  Proficiency and experience underlies of
performance for employees and capabilities for business by giving a
measure of growth, skills, behaviours, and knowledge that leads to
success.

The word "practice" often associates with "regularly repeated
actions" - sports exercises, cooking, text typing, vocabulary
repetition.

But just repeating a skill or task, even over a period of many years,
doesn’t build experience. Many people give up on learning a new skill
or only reach a middling level of competence because they are not
making much progress. That’s because once you reach a reasonable level
of competence and are able to do what you need to do, the skill
becomes automatic. At best, you’re maintaining your abilities, but not
improving them.

** NOTES                                                          :noexport:

* TODO Several definitions

*Practice* is a repetition of an activity to improve a skill.

*Deliberate practice* is a system of regularly repetitive conscious
learning activities that are conducted for improving an individual's
skills and performance that requires many cognitive efforts, maximum
focus. Deliberate practice is conducted with the goal of improving an
individual's productivity and build experience.


* TODO Real life samples

Benjamin Franklin: A self-educated writer.

Benjamin Franklin had been inspired by the quality and style of
articles in a British magazine he read, and wanted to improve his own
writing. He wide used the principles of deliberate practice into
action. He tried to replicate the texts from the magazine. To help
himself, he wrote short notes of the magazine’s content, so he could
be restored of the meaning of each sentence. Franklin wanted to create
his own articles by his own words that were just as detailed, witty,
and neatly written as the original. When he compared his work to the
original, he would identify common instances where his writing fell
short and refine this practice technique to focus on those particular
weaknesses.

Demosthenes: a statesman and the finest orator in ancient Greece.

As a young man, he suffered from speech impediment, but he was
determined to improve. According to legends, he spoke with pebbles in
his mouth, which made him exert super-hard to get the words
out. Practicing with stones improved his diction. And to improve the
projection of his voice, he practiced speeches while running and in
the backdrop of the roar of ocean.

Deliberate practice can be applied in many areas, such as music, arts,
science, when learning a new language, or when acquiring any kind of
challenging skill, whether intellectual or physical.

In music, the famous violinist Nathan Milstein said: “Practice as much
as you feel you can accomplish with concentration. Once when I became
concerned because others around me practiced all day long, I asked my
mentor how many hours I should practice, and he said, ‘It really
doesn’t matter how long. If you practice with your fingers, no amount
is enough. If you practice with your head, two hours is plenty.’”


* TODO Deliberate practice rules

1. Be inspired, engaged and motivated. It will helps in the hard parts
   of learning process - the frustration, the failures, the slow
   progres period;
2. Break the overall learning process down into small chunks;
3. Identify your weaknesses, test new strategies for each chunk;
4. Integrate your new learning experience into the overall process;
5. Delibarate practice requires recovery time. The process requires
   maximum focus and attention. It is challenging and impossible to do
   it all day long. The overall duration should not exeed 2 hours per
   day;
6. Search the constructive feedback and measurement. Good tutor can
   track your progress, find small ways to improve, and hold you
   accountable to delivering your best effort each day.

* TODO Conclusion

Regular repetition helps to improve speed, increased confidence but
doesn't improve our performance.

Mindness activity is the enemy of learning because our progress
becomes imaginated. We think what we are gained experience. But we
only reinforcing our current habits.

Deliberate practice have no immediate reward. Important to be
consistent and persistent.

Delibarate practice help us to maximize our potential.
