#+BEGIN_EXPORT html
---
layout: page
title: General Data Structures
tagline: " overview"
permalink: /fundamentals/data-structures-overview.html
categories: [Data Structuries, Fundamentals]
tags: [python, data structuries, dictionaries]
---
#+END_EXPORT
#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+PROPERTY: header-args :exports both
#+PROPERTY: header-args+ :results output pp
#+PROPERTY: header-args+ :eval no-export
#+TOC: headlines 2

* Preamble

In computer science, a *data structure* is a systematic way of
organizing, managing, and storing data on a computer to facilitate
efficient access and modification. Data structures are critical for
designing efficient algorithms and software applications, as they
provide specific mechanisms that dictate how data is arranged in
memory and how it can be retrieved and manipulated.

Different data structures are tailored to solve various computational
problems efficiently. The choice of a data structure directly impacts
the performance of operations like searching, insertion, deletion, and
traversal. Common types of data structures include arrays, linked
lists, stacks, queues, trees, graphs, heaps, hash tables, and
more. Each structure has its own strengths and weaknesses, making it
suitable for particular use cases.


* The Common Data Structures in Computer Science

** Linear Data Structures

  1. *Array*:

     A collection of elements of the same data type stored in
     contiguous memory locations, allowing for constant-time access to
     elements via their index.

  2. *Linked List*:

     A sequence of elements where each element, called a node,
     contains a value and a reference (or pointer) to the next node in
     the sequence. This structure allows for efficient insertion and
     deletion operations, as they can be performed in constant time if
     the position is known, but access time is linear.

  3. *Stack*:

     A linear data structure that follows the Last In, First Out
     (LIFO) principle. Elements are added to the top of the stack
     using a push operation and removed from the top using a pop
     operation. This structure is commonly used for function call
     management, undo mechanisms in software, and syntax parsing.

  4. *Queue*:

     A linear data structure that follows the First In, First Out
     (FIFO) principle. Elements are added to the rear of the queue
     using an enqueue operation and removed from the front using a
     dequeue operation. Queues are used in task scheduling, buffering
     data streams, and handling asynchronous data transfers.





** Arrays

#+begin_quote
/Array/ is a linear data structure that stores a collection of items
of same data type in contiguous memory locations.
#+end_quote

/Linear data structures/ are a type of data structure in computer
science where data elements are arranged sequentially or
linearly. Each element has a previous and next adjacent, except for
the first and last elements.


#+begin_example
A real-world analogy for an array data structure is a parking lot. You
can look at the parking lot as a whole and treat it as a single
object, but inside the lot there are parking spots indexed by a unique
number. Parking spots are containers for vehicles—each parking spot
can either be empty or have a car, a motorbike, or some other vehicle
parked on it.
#+end_example

/Array index/: In an array, elements are identified by their
indexes. Array index starts from 0.

/Array element/: Elements are items stored in an array and can be
accessed by their index.

/Array Length/: The length of an array is determined by the number of
elements it can contain.

#+begin_src python
  # Find The Lowest Value in an Array
  my_array = [5, 11, 8, 3, 12]
  minVal = my_array[0]
  for i in my_array:
      if i < minVal:
          minVal = i
  print('Lowest value: ',minVal)

#+end_src

#+RESULTS:
: Lowest value:  3

** Linked Lists

A /Linked List/ is a data structure that consists of a series of nodes
connected by pointers. Each node in a linked list contains two main
components:

- /Data/: This holds the actual value or data associated with the node;
- /Next Pointer/: This stores the memory address (reference) of the next
  node in the sequence.

The way they are linked together is that each node points to where in
the memory the next node is placed.

A linked list is a collection of nodes. The first node is called the
/head/, and it’s used as the starting point for any iteration
through the list. The last node must have its next reference
pointing to /None/ to determine the end of the list.

***  The Double Linked List

The /Double Linked List/ is the Linked List with an extra: cells have
two pointers: one to the cell that came before it, and other to the
cell that comes after.


** Queues or Stacks

/Queue/ and /stacks/ differ only in the way elements are
retrieved. For a /queue/, you use a /First-In/First-Out (FIFO)/
approach. That means that the first element inserted in the list is
the first one to be retrieved.

For a /stack/, you use a /Last-In/First-Out (LIFO)/ approach, meaning
that the last element inserted in the list is the first to be
retrieved.

** Graph

/Graph/ is a non-linear data structure which are collection of nodes
(also called vertices) and edges (connections between nodes) that can
represent various relationships and pathways. Graphs are used to model
networks, such as social networks, transport systems, and the
internet.

The graphs components:

- /Vertices/: These are the points or nodes in the graph where edges
  begin ot end.

  Example: In a social network graph, a vertice could represent a
  person.

- /Edges/: Is simply a connection between two vertices, indicating a
  relationship or interaction between them.

  Example: In a social network graph, an edge could represent a
  friendship between two people.

#+begin_example
Imagine a game of football as a web of connections, where players are
the nodes and their interactions on the field are the edges.
#+end_example

Basic Operations on Graphs:

- Insertion of Nodes/Edges in the graph;
- Deletion of Nodes/Edges in the graph;
- Searching on Graphs;
- Traversal of Graphs.


** Tree

A /tree data structure/ is a collection of nodes that are connected by
edges and has a hierarchical relationship between the nodes.

The key components and properties of a tree data structure include:

- Node: A basic unit of a tree that contains data and references to
  child nodes;
- Root: The topmost node in a tree, which does not have a parent;
- Edge: The connection between two nodes, indicating a parent-child
  relationship;
- Leaf: A node that does not have any children;
- Internal Node: A node that has at least one child;
- Subtree: A tree consisting of a node and its descendants;
- Height: The length of the longest path from the root to a leaf;
- Depth: The length of the path from the root to a given node;
- Degree: The number of children of a node;



** Heap data structure

A /Heap/ is a special Tree-based Data Structure in which the tree is a
complete binary tree.

A /complete binary tree/ is a special type of binary tree where all
the levels of the tree are filled completely except the lowest level
nodes which are filled from as left as possible.

There are two main types of heaps:

- /Max-Heap/: In this heap, the value of the root node must be the
  greatest among all its child nodes and the same thing must be done
  for its left and right sub-tree also;
- /Min-Heap/: In this heap, the value of the root node must be the
  smallest among all its child nodes and the same thing must be done
  for its left and right sub-tree also










* Classification

IMG and description

* Notes                                                            :noexport:

** Glossary

/Abstract data/: refers to a mathematical concept that defines a set
of possible values and a set of operations that can be performed on
those values.

/Data Structures/: is a way of organizing and storing data in a
computer so that it can be accessed and used efficiently. It refers to
the logical or mathematical representation of data, as well as the
implementation in a computer program;

/Hash/: is a mathematical function that transforms a string of
characters or data of arbitrary size into a fixed-size value or key,
known as /a hash value/, /hash code/, /hash digest/, or simply /hash/.


A /hash value/ is a string of characters and numbers that is the
result of a hash function applied to a given input, such as a file or
a message. It is a /unique numerical value/ that identifies the
contents of the input and can be used to verify the integrity of the
data.

/Hashable object/: is an object that has a hash value which never
changes during its lifetime.

/Hashability/ is important because it allows objects to be used as
keys in dictionaries and members in sets. These data structures use
the hash value internally to efficiently store and retrieve data.

Mutable/immutable??

Some examples of hashable objects in Python include: Immutable
built-in types like integers, floats, strings, and tuples.

On the other hand, mutable objects like lists and dictionaries are not
hashable because their hash value can change during their lifetime.
While dictionaries themselves are not hashable, they require their
keys to be hashable in order to leverage efficient hash table
implementations.

** Abstract data types

#+begin_quote
/Abstract data type/ is a type (or class) for objects whose behavior
is defined by a set of values and a set of operations.

The definition of ADT only mentions what operations are to be
performed but not how these operations will be implemented. It does
not specify how data will be organized in memory and what algorithms
will be used for implementing the operations. It is called “abstract”
because it gives an implementation-independent view.

So a user only needs to know what a data type can do, but not how it
will be implemented. Think of ADT as a black box which hides the inner
structure and design of the data type.
#+end_quote

An Abstract Data Type only describes how variables of a given data
type are operated. It provides a list of operations, but doesn’t ex-
plain how data operations happen.

A List is a widely-used Abstract Data Type (ADT) that represents an
ordered collection of elements.

Commonly defined operations in a List ADT include:

- insert n, e : insert the item e at position n,
- remove n : remove the item at position n,
- get n : get the item at position n,
- sort : sort the items in the list,
- slice start, end : return a sub-list slice starting at the position
  start up until the position end,
- reverse : reverse the order of the list.


  https://realpython.com/python-hash-table/
  [[https://www.eecs.umich.edu/courses/eecs380/ALG/niemann/s_has.htm]]
