#+BEGIN_EXPORT html
---
layout: page
title: Learning English Grammar with British Council
tagline: " improve your English skills"
permalink: /english/english-grammar.html
categories: [English, Grammar]
tags: [english, grammar]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t eval:noexport
#+TOC: headlines 2
#+TODO: | AMPLE
#+TODO: RAW Init DP0 Todo DP1 Active | DONE
#+TODO: DELAY LAG RETARD | BARE

* DP0 Pronouns
SCHEDULED: <2024-04-23 Tue>

*Pronouns* is a word that stands in for noun, often to avoid the need
to repeat the same noun over and over.

** Subject and object pronouns

| Subject | Object |
|---------+--------|
| I       | me     |
| you     | you    |
| he      | him    |
| she     | her    |
| it      | it     |
| we      | us     |
| you     | you    |
| they    | them   |


*Subject pronouns* used as the subject of a verb, which means that
it's the person or thing *performing* the *action*.

I like the sunny days.
You are waiting for the bus.
He is a doctor.
It is the beautiful weather today.
She is walking with children.
We live in Ramelton.
They going to the shop.

*Object pronouns* used as grammatical objects of the verb. An object
pronoun receives the action instead of doing the action itself.

She is waiting for me.
I'll get it for you.
Give it to him.
Why are you looking at her?
Don't take it from us.
I'll speak to them.

I cooked it for you.
I'll tell him about your visit.
i'll be happy to see her.
This parsel for me.
Please buy some ice cream for us in grocery shop.
Please give them the letter.

*** Differnces between subject and object pronouns

A subject pronoun (I, we, he, she, they, or WHO) refers to the person
or thing that *performs an action*. It normally appears at the start
of a sentence, before the verb.

An object pronoun (me, us, him, her, them, or WHOM) refers to the
person or thing *affected by an action*. It normally comes after a
verb or preposition.

All other pronouns (e.g., “you,” “it or “WHAT”) and nouns have only
one form, which is used for both cases.

** DP0 =it= and =there= as dummy subjects
SCHEDULED: <2024-04-24 Wed>

English clauses always have a =subject=:

His father has just retired. > He was a teacher. (NOT Was a teacher.)

... except for the imperative:

    Go away.
    Play it again, please.

    =there=

If there is no other subject, we use =there= to talk about:

- where or when something is:

  There's an interesting book on the shelf.

- a number or amount:

 There is plenty of bread left.
 There were twenty people at the meeting.


- something existing or happening:

 There's a small problem.
 There was a nasty fight.

=it=

We use it to talk about:

- times and dates:

 It's nearly one o'clock.
 It's my birthday.

- the weather:

 It's raining.
 It's a lovely day.
 It was getting cold.

We use =it= with the verb =be= and an =–ing= form or
=to-infinitive= to express opinions:

 It's great living here.
 It's nice to meet you.

** Possessive pronouns

Is a pronoun that is used to express ownership or possession.

| Subject | Object | Possessive adjective | Possesssive pronoun |
|---------+--------+----------------------+---------------------|
| I       | Me     | my                   | mine                |
| you     | you    | your                 | yours               |
| he      | him    | his                  | his                 |
| she     | her    | her                  | hers                |
| it      | it     | its                  | -                   |
| we      | us     | our                  | ours                |
| they    | them   | their                | theirs              |


We can use a possessive pronoun instead of a full noun phrase to avoid
repeating words:

 Is that John's car?
 No, it's mine. (INSTEAD OF No, it's [my car].)

 Whose coat is this?
 Is it yours? (INSTEAD OF Is it [your coat]?)

 Her coat is grey.
 Mine is brown. (INSTEAD OF [My coat] is brown.)

** Demonstratives

A *demonstrative* is a pronoun that points to a particular noun or to
the noun it replaces.

=this and these=

We use =this= (singular) and =these= (plural) as pronouns:

- to talk about people or things near us:

  This is a nice cup of tea.
  Whose shoes are these?

- to introduce people:

  This is Janet.
  These are my friends John and Michael.

- to begin a conversation on the phone:

  Hello, this is David. Can I speak to Sally?

 =that and those=

We use that (singular) and those (plural) as pronouns to talk about
things that are not near us:

What's that?
Those are very expensive shoes.
This is our house, and that's Rebecca's house over there.

We also use that to reply to something someone has said:

'Shall we go to the cinema?'  'Yes, that’s a good idea.'
'I've got a new job.'  'That's great.'
'I'm very tired.'  'Why is that?'

With nouns

We can also use =this, these, that= and =those= with nouns.

We use =this= and =these= for people or things near us:

We have lived in this house for twenty years.
Have you read all of these books?

and =that= and =those= for people or things that are not near us:

Who lives in that house?
Who are those people?

** ='one'= and ='ones'=

We use =one= (singular) and =ones= (plural):

- after an =adjective=:

  - See those two girls? Helen is the tall /one/ and Jane is the short
    /one/.
  - Which is your car, the red /one/ or the blue /one/?
  - My trousers are torn. I need some new /ones/.

- after =the=:

  - See those two girls? Helen is the /one/ on the left.

- after =which= in questions:

  - You can borrow a book. Which /one/ do you want?
  - Which /ones/ are yours?

** Pronouns in questions

We use =who= to ask about people:

Who is that?
Who lives here?
Who did you see?

We use =whose= to ask about possession:

Whose coat is this?    or   Whose is this coat?
Whose book is that?   or   Whose is that book?
Whose bags are those?  or   Whose are those bags?

We use =what= to ask questions about things:

What is that?
What do you want?

We use =which= to ask someone to choose something:

Which came first, the chicken or the egg?
I've got two books. Which do you want?

We can also use =what= and =which= with nouns:

What subjects did you study at school?
What newspaper do you read?
Which newspaper do you read – The Times or The Guardian?
Which book do you want?
Which one is yours?

We often have a preposition at the end of a question:

Who does this book belong to?
What are you looking for?
Which university did you go to?

** Reflexive pronouns

*Reflexive pronouns* are words ending in -self or -selves that are
used when the subject and the object of a sentence are the same (e.g.,
I believe in myself).

| singular | myself    | yourself   | himself    | herself | itself |
|----------+-----------+------------+------------+---------+--------|
| plural   | ourselves | yourselves | themselves |         |        |


I fell over and hurt myself.
Be careful with that knife. You might cut yourself.

We use reflexive pronouns as an indirect object when the indirect
object is /the same as the subject of the verb/:

Would you like to pour yourself a drink?
We’ve brought ourselves something to eat.

We use reflexive pronouns as the /object of/ a =preposition= when the
object is the same as the subject of the verb:

They had to cook for themselves.
He was feeling very sorry for himself.

** Reciprocal pronouns

[rəˈsiprək(ə)l]

/Reciprocal pronouns/ are pronouns that indicate a mutual relationship
between two or more people or things. The only reciprocal pronouns in
English are /each other/ and /one another/.

We use the reciprocal pronouns /each other/ and /one another/ when two
or more people do the same thing.

- Peter and Mary helped each other. = Peter helped Mary and Mary
  helped Peter.
- We sent one another Christmas cards. = We sent them a Christmas card
  and they sent us a Christmas card.

 When to use /each other/ and /one another/ depends on the number of
 people or things involved in the action.

 /each other/ is more commonly used when referring to two people.

 - John and Jane are fighting with each other.

  while /one another/ is used when referring to more than two people.

  - The team members are helping one another.


** Indefinite pronouns

*Indefinite pronouns* in English are pronouns that refer to people,
places, or things in a general, non-specific way.

anybody   everybody   nobody  somebody
anyone    everyone   no one  someone
anything  everything  nothing  something

We use pronouns ending in -body or -one for people, and
pronouns ending in -thing for things:

- I opened the door but there was /no one/ at home.
- It was a very clear day. We could see /everything/.
- /Everybody/ enjoyed the concert.

  Be careful!
      
  In negative clauses, we use pronouns with no-, not pronouns with
  any-:

  - /Nobody/ came. (NOT Anybody didn't come.)

  We do not use another negative in a clause with nobody, no one or
  nothing:

  - /Nobody/ came. (NOT Nobody didn't come.)
  - /Nothing/ happened. (NOT Nothing didn't happen.)

We can add 's to an indefinite pronoun to make a possessive:

- Is this /anybody's/ coat?

We use else after indefinite pronouns to refer to other people or
things:

- If Michael can't come, we'll ask /somebody else/.
- I think this is /somebody else's/ coat.




  
