#+BEGIN_EXPORT html
---
layout: page
title: Python programming language
tagline: " brief overview"
permalink: /python/python-programming-language-intro.html
categories: [Python, Definitions]
tags: [python, intro]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t eval:noexport
#+TOC: headlines 2

* Preamble

* The Programming Pillars:

Input/Output
Assignment
Comparison operations
Control flow operations
Procedures
Miscelellaneous

** What means =input/output= in Python?

#+begin_quote
Input/Output (I/O) in Python refers to the process of taking input
from the user or external sources and displaying output to the user or
saving it to a file.
#+end_quote

#+begin_quote
There are no specific keywords in Python dedicated solely for
input/output (I/O) operations. Python's I/O functionality is primarily
handled using built-in functions like ~input()~ and ~print()~ rather
than reserved keywords.
#+end_quote

** What means =assignment= in Python?

#+begin_quote
In Python, assignment refers to the process of binding a name to a
value or object.
#+end_quote

#+begin_quote
Python's assignment functionality is primarily handled using the
assignment operator (=) and various augmented assignment operators
like +=, -=, *=, etc.

The /keywords/ that are most closely related to assignment in Python
are:

~del~: Used to delete a variable or remove elements from a list,
tuple, or dictionary;

~global~: Used to declare a variable as global inside a function;

~nonlocal~: Used to declare a variable as non-local inside a nested
function.
#+end_quote

** What means =comparison= operation in Python?

#+begin_quote
Comparison operations in Python refer to the use of comparison or
relational operators to compare variables or values. These operators
are essential in Python for making decisions based on conditions and
for controlling the flow of a program.

Python comparison operators include:
== (Equal to): Returns true if the two operands are equal.

!= (Not equal to): Returns true if the two operands are not equal.

> (Greater than): Returns true if the value of the left operand is
greater than the right operand.

< (Less than): Returns true if the value of the left operand is less
than the right operand.

>= (Greater than or equal to): Returns true if the value of the left
operand is greater or equal to the right operand.

<= (Less than or equal to): Returns true if the value of the left
operand is less or equal to the right operand.
#+end_quote

** What is =control flow operations= in programming? 

/Control flow/ is the /order/ in which individual statements,
instructions or function calls of an imperative program are executed
or evaluated.

Python provides several control flow constructs:

Conditional statements:

- ~if~ statement: Executes a block of code if a condition is True;
- ~if-else~ statement: Executes one block of code if a condition is
  True, and another block if it's False;
- ~if-elif-else~ statement: Allows checking multiple conditions.

Loops:

- ~for~ loop: Iterates over a sequence (like a list or string);
- ~while~ loop: Executes a block of code as long as a condition is
  True.

Transfer statements:

- ~break~ statement: Terminates the current loop and resumes execution
  at the next statement;
- ~continue~ statement: Skips the current iteration of a loop and
  moves to the next iteration.

The ~pass~ statement:

The body of a Python compound statement cannot be empty — it must
contain at least one statement. The ~pass~ statement, which performs
no action, can be used as a placeholder when a statement is
syntactically required but you have nothing specific to do.

Exception handling statements:

Python supports exception handling with the ~try~ statement, which
includes ~try~, ~except~, ~finally~, and ~else~ clauses.

** What is =procedures= in Python?

In Python, "procedures" typically refer to functions that perform
specific tasks or operations. Procedures (or functions)
are fundamental building blocks that allow you to encapsulate code
into reusable and modular units.

These keywords enable the creation and manipulation of functions:

~def~: Used to define a function;

~return~: Used to return a value from a function;

~yield~ Is a powerful tool for creating generators. It's used when you
need to iterate over a sequence of values efficiently

* Definitions

** What is a programming language whatever?

#+begin_quote
A programming language is a set of instructions used by programmers to
communicate with computers.
#+end_quote

** What are the components of a Python programming language?

- /Character Set/: The character set in Python includes letters (A-Z or
  a-z), digits (0-9), special symbols (such as ., @, #, %, etc.), and
  white spaces (like blank space, horizontal tab, carriage return, new
  line, and form feed);
- /Data Types/: Python supports various data types, which are the types
  of values that can be stored and manipulated in a program. The
  type() function is used to get the data type of any object or
  variable;
- /Constants/: are fixed values that remain unchanged during the
  execution of a program and are used in assignment statements;
- /Variables/: are data items whose values may vary during the
  execution of the program;
- /Keywords/: are words that have been assigned specific meanings in
  the context of Python language programs and should not be used as
  variable names to avoid problems. There are 35 keywords in the
  Python programming language;
- /Expressions/: are phrases of code that Python evaluates to produce
  a value;
- /Statements/: are logical units of code that can be executed by the
  Python interpreter. They can be assignment statements, conditional
  statements, loops, or function calls;
- /Comments/: are additional readable information that is ignored by the
  Python interpreter. They begin with the # symbol and end with the
  end of the physical line;
- /Functions/: are blocks of code that can be called multiple times from
  different parts of a program;
- /Blocks and identation/: Python uses indentation to mark blocks of
  code. This is a distinctive feature of Python and is used to define
  the scope of control structures like if-else statements and loops;
- /Operators/: are symbols or keywords that perform mathematical,
  logical, or comparison operations on data;
- /Control Structures/: are used to control the flow of a Python
  program. They include conditionals (if-else statements), loops
  (for/while statements), and exceptions (try/except blocks.
  

** What is Python programming language?

#+begin_quote
/Python/ is an interpreted, object-oriented, high-level /programming
language/ with dynamic semantics.
#+end_quote

** What is interpretation in programming?

#+begin_quote
/Interpretation/ in programming refers to the process where a computer
program, known as an interpreter, directly executes instructions
written in a programming or scripting language without the need for
prior compilation into machine code.
#+end_quote

** What is compilation in programming?

#+begin_quote
/Compilation/ in programming refers to the process of translating a
program written in a high-level programming language, known as source
code, into object code that a computer can understand.
#+end_quote

** Is Python interpreted or compiled programming language?

Python is both an interpreted and compiled language.

In /Interprereted Programming Language/ the source code is executed by
an interpreter which translates code into machine code on the fly.

/Compilation/ is the process of translating source code written in a
high-level programming language into a lower-level language, such as
machine code, that can be executed by a computer.

Python allows you to save the compiled bytecode to .pyc files. This
speeds up startup time on subsequent runs since the source code
doesn't need to be recompiled. When you are execute any Python script
the =.pyc= (compiled bytecode file) generated. If you run the script
again (without making changes) =.pyc= file will not be
regenerated. After execution modified script =.pyc= the file will be
generated again. Compilation carried out to increase the speed of
program execution.

** What is programming paradigm?

#+begin_quote
A model of something, or very clear and typical example of something.
#+end_quote

#+begin_quote
A /programming paradigm/ is a method or style of programming that
defines a set of principles, techniques, and patterns for structuring
code to solve problems on a computer.
#+end_quote

#+begin_quote
A /programming paradigm/ refers to a high-level approach used to
structure and conceptualize the implementation of computer programs.
#+end_quote


** What is object-oriented programming language?

#+begin_quote
/Object-oriented programming (OOP)/ is a programming paradigm based on
the concept of objects, which can contain data (attributes or
properties) and code (methods).
#+end_quote

** What is high-level programming language?

#+begin_quote
A /high-level programming language/ (HLL) is a programming language
that is designed to be easier for humans to read, write, and
understand, while still being able to be executed by a computer
#+end_quote

#+begin_quote
In /High-Level programming language/ it may use natural language
elements, be easier to use, or may automate significant areas of
computing systems, making the process of developing a program simpler
and more understandable.
#+end_quote

** What is General-Purpose language?

#+begin_quote
Python is /General-Purpose language/. It means that you can use Python
in various domains including: Web applications, Big data applications,
Testing, Automation, Data science, machine learning, and AI, Desktop
software, Mobile apps etc.
#+end_quote

** What is Python Interpreter?


** The Python interpreter

It is a computer program that converts high-level Python program
statements into machine code. The Python interpreter is usually
installed as ‘/usr/local/bin/python3.11’ on those machines where it is
available; The interpreter operates somewhat like the Unix shell: when
called with standard input connected to a tty device, it reads and
executes commands interactively.

This** Keywords

/Python keywords/ are reserved words in the Python programming
language that have special meanings and purposes. These keywords
cannot be used as variable names, function names, or any other
identifiers within Python code.

False      await      else       import     pass
None       break      except     in         raise
True       class      finally    is         return
and        continue   for        lambda     try
as         def        from       nonlocal   while
assert     del        global     not        with
async      elif       if         or         yield

** Keywords categorization by their usage

| Control flow |                                                    |
|--------------+----------------------------------------------------|
| if           | Conditional execution                              |
| elif         | Allows checking multiple conditions                |
| else         | Else condition                                     |
| for          | Looping over sequences                             |
| while        | Looping with a condition                           |
| break        | Exit the loop                                      |
| continue     | Skip the rest iteration and continue with the next |
| pass         | Do nothing statement                               |
| return       | Return a value from function                       |
| yield        | Return a generator                                 |
| try          | Start of exception handling                        |
| except       | Catch an exception                                 |
| finally      | Execute code even if exception occurred            |
| raise        | Raise an exception                                 |


* Questions
** Is Python compiled language?
** Is Python interpreted language?
* Data model
** Objects, values and types

/Objects/ are Python’s abstraction for data.  All data in a Python
program is represented by objects or by relations between objects.

Every object has an identity, a type and a value.

*** Object identity

Object identity refers to the unique integer value that identifies an
object. This identity is unique during the lifetime of the object and
remains constant throughout its lifetime. It can be thought of as the
object's address in memory.

~is~ operator compares the identity of two objects; the ~id()~
function returns an integer representing its identity.

#+begin_src python :results output
  a = 10
  b = 15
  print(id(a))
  print(id(b))
#+end_src

#+RESULTS:
: 10861480
: 10861640

#+begin_src python :results output
  a = [1, 2, 3]
  b = a
  c = [1, 2, 3]
  print(a is b)
  print(a is c)
  print(a == c)
#+end_src

#+RESULTS:
: True
: False
: True

Use ~is~ to check if two variables reference the same object;
Use == to check if two variables have the same value.

*** An object's type and value

An object’s type determines the operations that the object supports
and also defines the possible values for objects of that type.
~type()~ function returns an object’s type. Like its identity, an
object’s ‘type’ is also unchangeable.

#+begin_src python :results output
  x = 5
  print(type(x))
#+end_src

#+RESULTS:
: <class 'int'>

The ‘value’ of some objects can change. Objects whose value can change
are said to be /mutable/; objects whose value is unchangeable once
they are created are called /immutable/. Numbers, strings and tuples
are /immutable/, while dictionaries and lists are /mutable/.

* Notes                                                            :noexport:


A *programming paradigm* is a method or style of programming that
defines a set of principles, techniques, and patterns for structuring
code to solve problems on a computer. Programming paradigms can be
classified into different categories, such as: Imperative
paradigm. Declarative paradigm. Object-oriented paradigm.

#+begin_quote
In *object-oriented* programming language a programming paradigm based
on the concept of "objects", which may contain data, in the form of
fields, often known as attributes; and code, in the form of
procedures, often known as methods. For example, a person is an object
which has certain properties such as height, gender, age, etc.
#+end_quote


