#+BEGIN_EXPORT html
---
layout: page
title: SSH connection into a remote host in Linux
tagline: " how it works"
permalink: /linux/debian/SSH-connection.html
categories: [Linux, Debian12, SSH]
tags: [Linux, Debian12, ssh]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+TODO: | AMPLE
#+TODO: RAW INIT TODO ACTIVE | DONE
#+TODO: DELAY LAG RETARD | BARE

* Introduction

 ssh (SSH client) is a program for logging into a remote machine and
 for executing commands on a remote machine. It is intended to
 provide secure encrypted communications between two untrusted
 hosts over an insecure network.

 When a secure SSH connection is established, a shell session
 starts. It enables manipulating the remote machine (server) by typing
 commands within the client on your local computer.

* Prerequisites

- The remote computer must be turned on and have a network connection;

- The SSHd program must be running;

- You must to know the IP address or the name of the remote machine;

- You must to have permission to access the remote computer;

- You must to know user's name and password for logging.

* [#A] How to Connect via SSH
SCHEDULED: <2024-04-17 Wed>
:PROPERTIES:
:CATEGORY: Linux
:END:

#+begin_src sh
  ssh [username]@[host_ip_address]
#+end_src

* How to verify that SSH server is running

#+begin_src sh
  ps -aux | grep ssh
#+end_src

You can manually start it by running

#+begin_src sh
  sudo service sshd start
#+end_src
