#+BEGIN_EXPORT html
---
layout: page
title: Essential Database Fundamentals
tagline: " mastering the basics"
permalink: /database-fundamentals.html
categories: [Linux, Database, SQL]
tags: [linux, database, sql]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Introduction
* Definitions

#+begin_quote
*Data base" refers to an organized collection of data stored and
 accessed electronically, typically managed by a database management
 system (DBMS).
#+end_quote

#+begin_quote
 *A database* is a structured repository of information that allows
 efficient storage, retrieval, modification, and deletion of
 data.
#+end_quote

#+begin_quote
*Database management system* is a software system that enables users
 to define, create, maintain, and control access to databases.
#+end_quote

* Databases types and examples

- /Hierarchical Databases/: These databases organize data in a
  parent-child relationship, resembling a tree-like structure where
  each child record has only one parent. The Windows Registry is one
  example of this system.;
- /Relational Databases/: Based on the relational data model, these
  databases store data in rows and columns forming tables, allowing
  for multiple types of relationships between tables. his database
  commonly uses /Structured Query Language (SQL)/ for operations like
  creating, reading, updating, and deleting (CRUD) data. MySQL,
  PostgreSQL, Microsoft SQL Server, and Oracle are examples;
- /NoSQL Databases/ or /Non-relational/: These databases store data in
  various ways, not limited to tabular form, and emerged to meet the
  demands of modern applications.

  They are further categorized into:
  - document databases;
  - key-value stores;
  - column-oriented databases;
  - graph databases.
    
   Examples include MongoDB and Redis;
- /Object-oriented Databases/: These databases store data using the
  object-based data model approach, representing and storing data as
  objects similar to those used in object-oriented programming
  languages. One example of an object oriented database is MongoDB
  Realm;

