#+BEGIN_EXPORT html
---
layout: page
title: SSH connection to a remote host in Linux
tagline: " how it works"
permalink: /linux/debian/SSH-connection.html
categories: [Linux, Debian12, SSH]
tags: [Linux, Debian12, ssh]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+TODO: | AMPLE
#+TODO: RAW INIT TODO ACTIVE | DONE
#+TODO: DELAY LAG RETARD | BARE

* Introduction

 *ssh (SSH client)* is a program for logging into a remote machine and
 for executing commands on a remote machine. It is intended to provide
 secure encrypted communications between two untrusted hosts over an
 insecure network.

 SSH works by connecting a client program to an ssh server, called
 sshd.

 *sshd (OpenSSH Daemon)* is the daemon program for ssh. It provides
 secure encrypted communications between two untrusted hosts over an
 insecure network.

 When a secure SSH connection is established, a shell session
 starts. It enables manipulating the remote machine (server) by typing
 commands within the client on your local computer.


* Prerequisites

- The remote computer must be turned on and have a network connection;

- The SSHd program must be running;

- You must to know the IP address or the name of the remote machine;

- You must to have permission to access the remote computer;

- You must to know user's name and password for logging.

* [#A] How to Connect via SSH
SCHEDULED: <2024-04-16 Tue>
:PROPERTIES:
:CATEGORY: Linux
:END:
:LOGBOOK:
CLOCK: [2024-04-16 Tue 09:16]--[2024-04-16 Tue 10:08] =>  0:52
:END:

#+begin_src sh
  ssh UserName@IPAddressOrHostname
#+end_src

* How to verify that SSH server is running

#+begin_src sh
  ps -aux | grep sshd
#+end_src

or

#+begin_src sh
  systemctl status ssh
#+end_src


The process needed to start an ssh server depends on the distribution
of Linux that you are using. In Debian12 you can manually start it by
running:

#+begin_src sh
  sudo service ssh start
#+end_src

To stop the SSH host server, enter the following:

#+begin_src 
  sudo service ssh stop
#+end_src

* SSH port

SSH, by default, is configured to use port 22 for remote
communication. Note that it’s possible to configure a different port
for SSH.

