#+BEGIN_EXPORT html
---
layout: page
title: Fleeting notes elaboration
tagline: " how to cope with disorder
permalink: /org-agenda/niceties.html
categories: [Org-agenda, Task Management]
tags: []
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
* Preamble

What is fleeting notes:

Some informal notes on any thought or idea that pops into your mind
when you are reading something, browsing the web, thinking about
something.

These notes are fleeting, and for that reason, must be captured
quickly, or they will fleet away.

* Raw source for elaboration

The best and fastest way to master an unfamilar topic is to copying
and improving existing approaches, views, concepts. You find it, copy
it, improve it.

The notes are only reminders of information. Quickly write down what
you are thinking in any kind of way.

In Emacs the best approach is Org-capture templates usage. But at the
initial stage you can collect them into *scratch* buffer.

You must to come back to these notes when planning you Agenda for the
current or the next day. Most of them will be converted into your new
tasks. And you must to organize and manage them.

** Sense

 in the name of each task

 Semantically menaningful

** Task decomposition

#+begin_quote
Complex task can have many different and connected parts, components
and is therefore often difficult to understand or unimpossible to
resolve from the first time.
#+end_quote


#+begin_quote
Breaking tasks down helps us to see large tasks as more approachable
and doable, and reduces our propensity to procrastinate or delay
tasks, because we simply don't know where to begin.
#+end_quote

#+begin_quote
By breaking down complex tasks into manageable subtasks and
prioritizing them effectively, you can approach the work with a clear
roadmap. This approach allows for better organization, improved focus,
and increased productivity.
#+end_quote


** Check up the sense
