#+BEGIN_EXPORT html
---
layout: page
title: Python programming language
tagline: " brief overview"
permalink: /python/python-programming-language-intro.html
categories: [Python, Definitions]
tags: [python, intro]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t eval:noexport
#+TOC: headlines 2

* Preamble

* The Programming Pillars:

Input/Output
Assignment
Comparison operations
Control flow operations
Procedures
Miscelellaneous

** What means =input/output= in Python?

#+begin_quote
Input/Output (I/O) in Python refers to the process of taking input
from the user or external sources and displaying output to the user or
saving it to a file.
#+end_quote

#+begin_quote
There are no specific keywords in Python dedicated solely for
input/output (I/O) operations. Python's I/O functionality is primarily
handled using built-in functions like ~input()~ and ~print()~ rather
than reserved keywords.
#+end_quote

** What means =assignment= in Python?

#+begin_quote
In Python, assignment refers to the process of binding a name to a
value or object.
#+end_quote

#+begin_quote
Python's assignment functionality is primarily handled using the
assignment operator (=) and various augmented assignment operators
like +=, -=, *=, etc.

The /keywords/ that are most closely related to assignment in Python
are:

~del~: Used to delete a variable or remove elements from a list,
tuple, or dictionary;

~global~: Used to declare a variable as global inside a function;

~nonlocal~: Used to declare a variable as non-local inside a nested
function.
#+end_quote

** What means =comparison= operation in Python?

#+begin_quote
Comparison operations in Python refer to the use of comparison or
relational operators to compare variables or values. These operators
are essential in Python for making decisions based on conditions and
for controlling the flow of a program.

Python comparison operators include:
== (Equal to): Returns true if the two operands are equal.

!= (Not equal to): Returns true if the two operands are not equal.

> (Greater than): Returns true if the value of the left operand is
greater than the right operand.

< (Less than): Returns true if the value of the left operand is less
than the right operand.

>= (Greater than or equal to): Returns true if the value of the left
operand is greater or equal to the right operand.

<= (Less than or equal to): Returns true if the value of the left
operand is less or equal to the right operand.
#+end_quote

** What is =control flow operations= in programming? 

/Control flow/ is the /order/ in which individual statements,
instructions or function calls of an imperative program are executed
or evaluated.

Python provides several control flow constructs:

Conditional statements:

- ~if~ statement: Executes a block of code if a condition is True;
- ~if-else~ statement: Executes one block of code if a condition is
  True, and another block if it's False;
- ~if-elif-else~ statement: Allows checking multiple conditions.

Loops:

- ~for~ loop: Iterates over a sequence (like a list or string);
- ~while~ loop: Executes a block of code as long as a condition is
  True.

Transfer statements:

- ~break~ statement: Terminates the current loop and resumes execution
  at the next statement;
- ~continue~ statement: Skips the current iteration of a loop and
  moves to the next iteration.

The ~pass~ statement:

The body of a Python compound statement cannot be empty — it must
contain at least one statement. The ~pass~ statement, which performs
no action, can be used as a placeholder when a statement is
syntactically required but you have nothing specific to do.

Exception handling statements:

Python supports exception handling with the ~try~ statement, which
includes ~try~, ~except~, ~finally~, and ~else~ clauses.

** What is =procedures= in Python?

In Python, "procedures" typically refer to functions that perform
specific tasks or operations. Procedures (or functions)
are fundamental building blocks that allow you to encapsulate code
into reusable and modular units.

These keywords enable the creation and manipulation of functions:

~def~: Used to define a function;

~return~: Used to return a value from a function;

~yield~ Is a powerful tool for creating generators. It's used when you
need to iterate over a sequence of values efficiently


* Definitions

** What is a programming language whatever?

#+begin_quote
A programming language is a set of instructions used by programmers to
communicate with computers.
#+end_quote

** What is Python programming language?

#+begin_quote
/Python/ is an interpreted, object-oriented, high-level /programming
language/ with dynamic semantics.
#+end_quote

** What is interpretation in programming?

#+begin_quote
/Interpretation/ in programming refers to the process where a computer
program, known as an interpreter, directly executes instructions
written in a programming or scripting language without the need for
prior compilation into machine code.
#+end_quote

** What is compilation in programming?

#+begin_quote
/Compilation/ in programming refers to the process of translating a
program written in a high-level programming language, known as source
code, into object code that a computer can understand.
#+end_quote

** Is Python interpreted or compiled programming language?

Python is both an interpreted and compiled language.

In /Interprereted Programming Language/ the source code is executed by
an interpreter which translates code into machine code on the fly.

/Compilation/ is the process of translating source code written in a
high-level programming language into a lower-level language, such as
machine code, that can be executed by a computer.

Python allows you to save the compiled bytecode to .pyc files. This
speeds up startup time on subsequent runs since the source code
doesn't need to be recompiled. When you are execute any Python script
the =.pyc= (compiled bytecode file) generated. If you run the script
again (without making changes) =.pyc= file will not be
regenerated. After execution modified script =.pyc= the file will be
generated again. Compilation carried out to increase the speed of
program execution.

** What is programming paradigm?

#+begin_quote
A /programming paradigm/ is a method or style of programming that
defines a set of principles, techniques, and patterns for structuring
code to solve problems on a computer.
#+end_quote

#+begin_quote
A /programming paradigm/ refers to a high-level approach used to
structure and conceptualize the implementation of computer programs.
#+end_quote


** What is object-oriented programming language?

#+begin_quote
/Object-oriented programming (OOP)/ is a programming paradigm based on
the concept of objects, which can contain data (attributes or
properties) and code (methods).
#+end_quote

** What is high-level programming language?

#+begin_quote
A /high-level programming language/ (HLL) is a programming language
that is designed to be easier for humans to read, write, and
understand, while still being able to be executed by a computer
#+end_quote

#+begin_quote
In /High-Level programming language/ it may use natural language
elements, be easier to use, or may automate significant areas of
computing systems, making the process of developing a program simpler
and more understandable.
#+end_quote

** What is General-Purpose language?

#+begin_quote
Python is /General-Purpose language/. It means that you can use Python
in various domains including: Web applications, Big data applications,
Testing, Automation, Data science, machine learning, and AI, Desktop
software, Mobile apps etc.
#+end_quote

** What is Python Interpreter?


** The Python interpreter

It is a computer program that converts high-level Python program
statements into machine code. The Python interpreter is usually
installed as ‘/usr/local/bin/python3.11’ on those machines where it is
available; The interpreter operates somewhat like the Unix shell: when
called with standard input connected to a tty device, it reads and
executes commands interactively.

This** Keywords

/Python keywords/ are reserved words in the Python programming
language that have special meanings and purposes. These keywords
cannot be used as variable names, function names, or any other
identifiers within Python code.

False      await      else       import     pass
None       break      except     in         raise
True       class      finally    is         return
and        continue   for        lambda     try
as         def        from       nonlocal   while
assert     del        global     not        with
async      elif       if         or         yield

** Keywords categorization by their usage

| Control flow |                                                    |
|--------------+----------------------------------------------------|
| if           | Conditional execution                              |
| elif         | Allows checking multiple conditions                |
| else         | Else condition                                     |
| for          | Looping over sequences                             |
| while        | Looping with a condition                           |
| break        | Exit the loop                                      |
| continue     | Skip the rest iteration and continue with the next |
| pass         | Do nothing statement                               |
| return       | Return a value from function                       |
| yield        | Return a generator                                 |
| try          | Start of exception handling                        |
| except       | Catch an exception                                 |
| finally      | Execute code even if exception occurred            |
| raise        | Raise an exception                                 |



* Questions
** Is Python compiled language?
** Is Python interpreted language?
* Notes                                                            :noexport:


A *programming paradigm* is a method or style of programming that
defines a set of principles, techniques, and patterns for structuring
code to solve problems on a computer. Programming paradigms can be
classified into different categories, such as: Imperative
paradigm. Declarative paradigm. Object-oriented paradigm.

#+begin_quote
In *object-oriented* programming language a programming paradigm based
on the concept of "objects", which may contain data, in the form of
fields, often known as attributes; and code, in the form of
procedures, often known as methods. For example, a person is an object
which has certain properties such as height, gender, age, etc.
#+end_quote


