#+BEGIN_EXPORT html
---
layout: page
title: Tasks management
tagline: "How use your time more effectevily"
permalink: /meta-learning/tasks-management.html
categories: [Learning Methodology, Org-mode]
tags: [agenda, tasks-management]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: TM
#+TODO: | AMPLE
#+TODO: RAW INIT TODO ACTIVE | DONE

* [#A] Preface
SCHEDULED: <2024-01-29 Mon>
:LOGBOOK:
CLOCK: [2024-01-26 Fri 12:19]--[2024-01-26 Fri 12:38] =>  0:19
:END:
#+begin_quote
Task management skills are the abilities that help you work
efficiently and take full advantage of your time.
#+end_quote

#+begin_quote
Task management is the process of managing a task through its
lifecycle. It involves planning, testing, tracking, and
reporting. Task management can help either individual achieve goals,
or groups of individuals collaborate and share knowledge for the
accomplishment of collective goals. Tasks are also differentiated by
complexity, from low to high.  Effective task management requires
overseeing all aspects of a task, including its status, priority,
time, human and financial resource assignments, recurrence,
dependencies, notifications, etc.

Task management embraces several key activities.

The status of tasks can be described by these states: 

Task lifecycle

Ready
Assigned
Terminated
Expired
Forwarded
Started
Finished
Verified
Paused
Failed
#+end_quote

* [#A] Tasks classification
SCHEDULED: <2024-01-30 Tue>

- Main classes;
- Classes definition (purpose, distinction features);

The main tasks classes are:

Class I - by urgency and importancy:

Urgent and important - demand your attention and action right now;

Important, but not urgent - they are essential issues, but they’re
not urgent and  don’t require your immediate action. So these
are the items you’ll want to schedule work for a later time;

Not important, but urgent - these are urgent items that pop up and
demand immediate attention;

Not important, not urgent - they are not essential or urgent, so you
can, in most cases, delay them or delete from your list.

Class II - Chores:
It is regular, trivial, banal routine tasks that
important to do everyday or in particular day.

Class III - by dependency:
Related or Not related

Tasks whose execution depends on each other are considered *related*.
Сompleting one of these tasks is the key to completing the other task.

Class lV:
By complexity:
Complex or simple

Complex task can have many different and connected parts, and is
therefore often difficult to understand;

Simple is a task that easily understandd or done and presenting no
difficulty.

Class V:
By gestation stages:

RAW Init DP0 Todo DP1 Active DONE

* Org-Agenda as the main tool of capabilities
* Group your tasks into bundles
* Assign your tasks to a particular date/time
* Final preparation
