#+BEGIN_EXPORT html
---
layout: page
title: Learning English Grammar with British Council
tagline: " improve your English skills"
permalink: /english/english-grammar.html
categories: [English, Grammar]
tags: [english, grammar]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t eval:noexport
#+TOC: headlines 2
#+TODO: | AMPLE
#+TODO: RAW Init DP0 Todo DP1 Active | DONE
#+TODO: DELAY LAG RETARD | BARE

* DP0 Pronouns
SCHEDULED: <2024-04-23 Tue>

*Pronouns* is a word that stands in for noun, often to avoid the need
to repeat the same noun over and over.

** Subject and object pronouns

| Subject | Object |
|---------+--------|
| I       | me     |
| you     | you    |
| he      | him    |
| she     | her    |
| it      | it     |
| we      | us     |
| you     | you    |
| they    | them   |


*Subject pronouns* used as the subject of a verb, which means that
it's the person or thing *performing* the *action*.

I like the sunny days.
You are waiting for the bus.
He is a doctor.
It is the beautiful weather today.
She is walking with children.
We live in Ramelton.
They going to the shop.

*Object pronouns* used as grammatical objects of the verb. An object
pronoun receives the action instead of doing the action itself.

She is waiting for me.
I'll get it for you.
Give it to him.
Why are you looking at her?
Don't take it from us.
I'll speak to them.

I cooked it for you.
I'll tell him about your visit.
i'll be happy to see her.
This parsel for me.
Please buy some ice cream for us in grocery shop.
Please give them the letter.

*** Differnces between subject and object pronouns

A subject pronoun (I, we, he, she, they, or WHO) refers to the person
or thing that *performs an action*. It normally appears at the start
of a sentence, before the verb.

An object pronoun (me, us, him, her, them, or WHOM) refers to the
person or thing *affected by an action*. It normally comes after a
verb or preposition.

All other pronouns (e.g., “you,” “it or “WHAT”) and nouns have only
one form, which is used for both cases.

** DP0 =it= and =there= as dummy subjects
SCHEDULED: <2024-04-24 Wed>

English clauses always have a =subject=:

His father has just retired. > He was a teacher. (NOT Was a teacher.)

... except for the imperative:

    Go away.
    Play it again, please.

    =there=

If there is no other subject, we use there to talk about:

- where or when something is:

  There's an interesting book on the shelf.

- a number or amount:

 There is plenty of bread left.
    There were twenty people at the meeting.


- something existing or happening:

 There's a small problem.
    There was a nasty fight.

it

We use it to talk about:

- times and dates:

 It's nearly one o'clock.
 It's my birthday.

- the weather:

 It's raining.
 It's a lovely day.
    It was getting cold.

We use =it= with the verb =be= and an =–ing= form or
=to-infinitive= to express opinions:

 It's great living here.
 It's nice to meet you.

** Possessive pronouns

Is a pronoun that is used to express ownership or possession.

| Subject | Object | Possessive adjective | Possesssive pronoun |
|---------+--------+----------------------+---------------------|
| I       | Me     | my                   | mine                |
| you     | you    | your                 | yours               |
| he      | him    | his                  | his                 |
| she     | her    | her                  | hers                |
| it      | it     | its                  | -                   |
| we      | us     | our                  | ours                |
| they    | them   | their                | theirs              |


We can use a possessive pronoun instead of a full noun phrase to avoid
repeating words:

 Is that John's car?
      No, it's mine. (INSTEAD OF No, it's [my car].)

 Whose coat is this?
      Is it yours? (INSTEAD OF Is it [your coat]?)

 Her coat is grey.
         Mine is brown. (INSTEAD OF [My coat] is brown.)

** Demonstratives

A *demonstrative* is a pronoun that points to a particular noun or to
the noun it replaces.

=this and these=

We use =this= (singular) and =these= (plural) as pronouns:

- to talk about people or things near us:

  This is a nice cup of tea.
  Whose shoes are these?

- to introduce people:

  This is Janet.
  These are my friends John and Michael.

- to begin a conversation on the phone:

  Hello, this is David. Can I speak to Sally?

 =that and those=

We use that (singular) and those (plural) as pronouns to talk about
things that are not near us:

What's that?
Those are very expensive shoes.
This is our house, and that's Rebecca's house over there.

We also use that to reply to something someone has said:

'Shall we go to the cinema?'  'Yes, that’s a good idea.'
'I've got a new job.'  'That's great.'
'I'm very tired.'  'Why is that?'

With nouns

We can also use =this, these, that= and =those= with nouns.

We use =this= and =these= for people or things near us:

We have lived in this house for twenty years.
Have you read all of these books?

and =that= and =those= for people or things that are not near us:

Who lives in that house?
Who are those people?

** ='one'= and ='ones'=

We use =one= (singular) and =ones= (plural):

- after an =adjective=:

  - See those two girls? Helen is the tall /one/ and Jane is the short
    /one/.
  - Which is your car, the red /one/ or the blue /one/?
  - My trousers are torn. I need some new /ones/.

- after =the=:

  - See those two girls? Helen is the /one/ on the left.

- after =which= in questions:

  - You can borrow a book. Which /one/ do you want?
  - Which /ones/ are yours?
