#+AUTHOR:    Viktoriia Kosinova
#+TITLE:     Mental Athlete's Wife ToDo List
#+SUBTITLE:  Life in a plain text
#+EMAIL:     viqsiq@gmail.com
#+LANGUAGE: en
#+STARTUP: showall indent
#+PROPERTY: header-args :comments org

* Glossary:

#+begin_quote
an alphabetical list of /terms or words found in _or relating_ to a
specific subject/, text, or dialect, with explanations; a brief
dictionary.
#+end_quote

Naturally it should be filled up /initially/ without an alphabetical
order; and later rearranged into it. The most effective way to
accomplish the task is to utilize ~org-capture~ faculties.

Predictably that the single word or term contains a handful related
words or terms to define it; the /tree-like structure/ of ~Org~ file
allows to visualize this relationship with no interruptions.



* Computer
A computer is a programmable device that stores, retrieves, and
processes data.

A computer is a machine or device that performs processes,
calculations and operations based on instructions provided by a
software or hardware program.

** Software
Software is a set of computer programs and associated documentation
and data.

Software is a set of instructions, data, or programs used to operate a
computer and execute specific tasks.
#+begin_example
Software is a set of computer programs and associated documentation
and data used to operate computer and execute specific task.
#+end_example

** Hardware
Hardware (H/W), in the context of technology, refers to the physical
elements that make up a computer or electronic system and everything else
involved that is physically tangible.

#+begin_example
Hardware (H/W) refers to the physical elements that make up a computer
or electronic system that is physically *tangible*.
#+end_example

** Computer program

#+begin_example
A computer program is a sequence or set of instructions in a programming
language for a computer to execute. It is one component of software, which
also includes documentation and other *intangible* components.
#+end_example

*** Source Code

#+begin_src 
A computer program in its *human-readable* form is called source code.
#+end_src


* Science

#+begin_example

#+end_example

Science is a rigorous, systematic endeavor that builds and organizes
knowledge in the form of testable explanations and predictions about the
world.

Science is the systematic study of the structure and behaviour of the
natural and physical world, or knowledge obtained about the world by
watching it carefully and experimenting. 

* Computer Science

Computer science is the study of computers and computing, including
their theoretical and algorithmic foundations, hardware and software,
and their uses for processing information.

Computer science is the study of computers and how they work,
including software, hardware, and algorithms. An algorithm is a list
of instructions for completing a task.

* counting time
be counting (down) the minutes/hours/days


* The Big-O Notation
Is a way to describe the speed or complexity of a given algorithm.
If your current project demands a predefined algorithm, it's
important to understand how fast or slow it is compared
to other options.

* Exponential
Exponential means growing or increasing very rapidly.

* counting memory
Method for measuring working memory capacity.

* Recursion

Recursion means "defining a problem in terms of itself".
This can be a very powerful tool in writing algorithms.

Recursion is the process of defining a problem (or the solution
to a problem) in terms of (a simpler version of) itself.

* Brute force
relying on or achieved through the application of force, effort,
or power in usually large amounts instead of more efficient,
carefully planned, or precisely directed methods

* Backtracking
to go back to an earlier point in a sequence

* Heuristics
Involving or serving as an aid to learning, discovery, or
problem-solving by experimental and especially trial-and-error
methods

Arriving at a solution by trying different actions to see if they
produce the result that is wanted, rather than using strict rules

* Systems programming

System is “a set of things working together as parts of a
mechanism or an interconnecting network.”

Systems programming involves the development of the individual
pieces of software that allow the entire system to function
as a single unit.

* GUI
A graphical user interface (GUI) is a digital interface in which
a user interacts with graphical components such as icons, buttons,
and menus. In a GUI, the visuals displayed in the user interface
convey information relevant to the user, as well as actions that
they can take.

* Internet scripting
A script is a list of commands that are present within
the code of a website that defines how the website behaves
in response to certain click requests sent by the user

* Component integration
The process of ensuring that individual units of code interact
together according to specifications.

* Rapid prototyping
Is a group of techniques used to quickly fabricate a scale model
of a physical part .

* Numeric and Scientific programming
Discipline that sits at the interface between mathematical
analysis and scientific computing.

* Frozen binary executables
Frozen binary executables are packages that combine your
program's byte code and the Python interpreter into a
single executable program.

* Dynamic typing interlude
Dynamic typing means that the type of the variable is determined
only during runtime.

* pseudocode
Is a description of the steps in an algorithm using a mix of conventions of
programming languages (like assignment operator, conditional operator, loop)
with informal, usually self-explanatory, notation of actions and conditions.
Pseudocode is human-friendly code that cannot be understood by
a machine.

* model
Is a set of concepts that represents a problem and its char-
acteristics

* science
a body of facts learned by study or experience

* logic
The thought processes that have been established as leading to valid solutions to problems

*** Synonyms:
    intellection, ratiocination, reason, reasoning, sense

* concept
something imagined or pictured in the mind

* biconditional
a relation between two propositions that is true only when both
propositions are simultaneously true or false
* computer
