#+AUTHOR:    Viktoriia Kosinova
#+TITLE:     Mental Athlete's Wife ToDo List
#+SUBTITLE:  Life in a plain text
#+EMAIL:     viqsiq@gmail.com
#+LANGUAGE: en
#+STARTUP: showall indent
#+PROPERTY: header-args :comments org

* Glossary:

#+begin_quote
an alphabetical list of /terms or words found in _or relating_ to a
specific subject/, text, or dialect, with explanations; a brief
dictionary.
#+end_quote

Naturally it should be filled up /initially/ without an alphabetical
order; and later rearranged into it. The most effective way to
accomplish the task is to utilize ~org-capture~ faculties.

Predictably that the single word or term contains a handful related
words or terms to define it; the /tree-like structure/ of ~Org~ file
allows to visualize this relationship with no interruptions.


* Definition 1                                                        :drill:

Computer

** Answer
A computer is a programmable device that stores, retrieves, and
processes data.

A computer is a machine or device that performs processes,
calculations and operations based on instructions provided by a
software or hardware program.

* Definition 2                                                        :drill:

Software

** Answer

Software is a set of computer programs, instructions, associated
documentation and data.

* Definition 3                                                        :drill:

Hardware

** Answer

Hardware (H/W), in the context of technology, refers to the physical
elements that make up a computer or electronic system and everything
else involved that is physically tangible.

* Definition 4                                                        :drill:

Computer program

** Answer

A computer program is a sequence or set of instructions in a
programming language for a computer to execute. It is one component of
software, which also includes documentation and other *intangible*
components.

* Definition 5                                                        :drill:

Source code

** Answer

A computer program in its *human-readable* form is called source code.

* Definition 6                                                        :drill:

Science

** Answer

Science is a rigorous, systematic study that builds and organizes
knowledge in the form explanations about the world.

* Definition 7                                                        :drill:

Computer Science

** Answer

Computer science is the study of computers and computing, including
their theoretical and algorithmic foundations, hardware and software,
and their uses for processing information.

* Definition 8                                                        :drill:

The Big-O Notation

** Answer

Is a way to describe the speed or complexity of a given algorithm. If
your current project demands a predefined algorithm, it's important to
understand how fast or slow it is compared to other options.

* Definition 9                                                        :drill:

Systems programming

** Answer

System is “a set of things working together as parts of a mechanism or
an interconnecting network.”

Systems programming involves the development of the individual pieces
of software that allow the entire system to function as a single unit.

* Definition 10                                                       :drill:

GUI

** Answer

A graphical user interface (GUI) is a digital interface in which a
user interacts with graphical components such as icons, buttons, and
menus. In a GUI, the visuals displayed in the user interface convey
information relevant to the user, as well as actions that they can
take.

* Definition 11                                                       :drill:

Internet scripting

** Answer

A script is a list of commands that are present within the code of a
website that defines how the website behaves in response to certain
click requests sent by the user

* Definition 11                                                       :drill:

Pseudocode

** Answer

Pseudocode is human-friendly code that cannot be understood by a
machine. Pseudocode expresses computational process.

* Definition 12                                                       :drill:

Model

** Answer
Is a set of concepts that represents a problem and its characteristics.

* Definition 13                                                       :drill:

Principle

** Answer

A principle is a basic rule, belief or idea that guides you.


* Definition 14                                                       :drill:

Logic

** Answer

The thought processes that have been established as leading to valid
solutions to problems.


* Definition 15                                                       :drill:

Deliberate practice

** Answer

Is a system of repetitive consciouos activities that are conducted for
improving an idividual's skills and performance. It is demand many
mind efforts, maximum focus, patience and have no immediate effect.

