#+AUTHOR:    Viktoriia Kosinova
#+TITLE:     Mental Athlete's Wife ToDo List
#+SUBTITLE:  Life in a plain text
#+EMAIL:     viqsiq@gmail.com
#+LANGUAGE: en
#+STARTUP: showall indent
#+PROPERTY: header-args :comments org

* Glossary:

#+begin_quote
an alphabetical list of /terms or words found in _or relating_ to a
specific subject/, text, or dialect, with explanations; a brief
dictionary.
#+end_quote

Naturally it should be filled up /initially/ without an alphabetical
order; and later rearranged into it. The most effective way to
accomplish the task is to utilize ~org-capture~ faculties.

Predictably that the single word or term contains a handful related
words or terms to define it; the /tree-like structure/ of ~Org~ file
allows to visualize this relationship with no interruptions.


** Computer

Answer
A computer is a programmable device that stores, retrieves, and
processes data.

A computer is a machine or device that performs processes,
calculations and operations based on instructions provided by a
software or hardware program.


** Software

Software is a set of computer programs, instructions, associated
documentation and data used operate computers and execute specific
tasks.

** Hardware

Hardware (H/W), in the context of technology, refers to the physical
elements that make up a computer or electronic system and everything
else involved that is physically tangible.

** Computer program

A computer program is a sequence or set of instructions in a
programming language for a computer to execute. It is one component of
software, which also includes documentation and other *intangible*
components.


** Source code

A computer program in its *human-readable* form is called source code.

** Science

Science is a rigorous, systematic study that builds and organizes
knowledge in the form explanations about the world.

** Computer Science

Computer science is the study of computers and computing, including
their theoretical and algorithmic foundations, hardware and software,
and their uses for processing information.

** The Big-O Notation

Is a way to describe the speed or complexity of a given algorithm. If
your current project demands a predefined algorithm, it's important to
understand how fast or slow it is compared to other options.


** Systems programming

System is “a set of things working together as parts of a mechanism or
an interconnecting network.”

Systems programming involves the development of the individual pieces
of software that allow the entire system to function as a single unit.

** GUI

A graphical user interface (GUI) is a digital interface in which a
user interacts with graphical components such as icons, buttons, and
menus. In a GUI, the visuals displayed in the user interface convey
information relevant to the user, as well as actions that they can
take.


** Pseudocode

Pseudocode is human-friendly code that cannot be understood by a
machine. Pseudocode expresses computational process.


** Model

Is a set of concepts that represents a problem and its
characteristics.


Principle

A principle is a basic rule, belief or idea that guides you.

** Logic

The thought processes that have been established as leading to valid
solutions to problems.


** Deliberate practice

Is a system of repetitive consciouos activities that are conducted for
improving an idividual's skills and performance. It is demand many
mind efforts, maximum focus, patience and have no immediate effect.

** Software testing

Is a method to check whether the actual software product matches
expected requirement and to ensure that software product is Defect
free.

** Unit testing

Refers to tests that verify the functionlity of a specific section of
code to ensure that the specific function works as expected.

** Integrating testing

Is the phase in software testing in which individuals software modules
are compined and test as group with goal  to check their compatibility.

** Acceptance testing

Is a test conducted to determine if the requirements of a
specification or contract are met.

** Code review

Is a software quality assurance activity in which one or several
people check a program by viewing  and reading parts of its source
code.

** Software walkthrough

Is a form of software peer review in which a designer or programmer
leads members of the development team and other interested parties
thrpugh a software product. And the participant ask questions and make
comments about possible errors and other possible problems.


** An application

Is a computer program designed to carry out a specific task other than
one relating to the operation of the computer itself typically to be
used by end-users.

** Test

Is a procedure intended to establish the quality, performance or
reliability of something, especially before it is taken into
widespread use.

** Validation

The act of confirming something as true or correct. Checks that the
software product satisfies or fits intended use, i.e., the software
meets the user requirements.
"Are we building the right product?"

** Varification

Checks that the specifications are correctly implemented.
"Are we building the product right?"

** Assembly language

Is any low-level programming language with a very strong
correspondence between the instructions in the language and the
arcitecture's machine.

** A compiler

Is a computer program that translates computer code written in one of
programming language (the source language) into another language (the
target language).

** Programming language

Is a system of notation for writing computer programs.

** Function

Is a sequence of program instuction that performs a specific task.

** Module

Is a discrete piece of code that can be independently created and
maintained to be used in different systems.


** Central Processing Unit (CPU)

is the brain of a computer, containing all the circuitry needed to
process input, store data, and output results. The CPU is constantly
following instructions of computer programs that tell it which data to
process and how to process it.

** Debugging

Is a process of finding and resolving bugs within computer programs,
software or system.

** Debugger or debugging tool

Is a computer program used to test and debug other program.

** Passive testing

Verifying the system behavior without any interaction with the
software product. Testers only look at system log and traces.

** Dynamic testing

Executing programmed code with a given set of test cases.

** Test case

Is a specification of the inputs, execution conditions, testing
procedure and expected results that define a single test to be
executed.

** Test design

Defines "HOW" something can be tested. It is describes test strategy
or test plan.
